version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yarn install --frozen-lockfile
      - run:
          name: Run Prettier
          command: |
            yarn prettier --check .
      - run:
          name: Build
          command: |
            make
      - store_artifacts:
          path: ./public
          destination: /

workflows:
  version: 2
  build:
    jobs:
      - build
