version: 2
jobs:
  build:
    working_directory: /workdir
    docker:
      - image: docker:17.06.2-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run:
          name: Build application Docker image
          command: |
            docker build -t ryotakameoka/portfolio .
      - deploy:
          name: Push Docker image
          command: |
            docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
            docker push ryotakameoka/portfolio

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
