version: 2
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yarn install --frozen-lockfile
      - run:
          name: Run Prettier
          command: |
            yarn prettier --check .

workflows:
  version: 2
  build:
    jobs:
      - build
